[package]
name = "mars-vesting"
version = "0.1.0"
authors = ["larry <larry@delphidigital.io>"]
edition = "2021"
license = "UNLICENSED"
repository = "https://github.com/mars-protocol/periphery"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "1.1", features = ["stargate"] }
cosmwasm-schema = "1.1"
cw2 = "0.15"
cw-storage-plus = "0.15"

[dev-dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }

[profile.release]
overflow-checks = true
